module.exports = {
  title: "WhatIsThis' Blog?",
  description: "Welcome to my dev Blog",
  author: "Whatisthis",
  siteUrl: "https://devhudi.github.io/gatsby-starter-hoodie/",
  links: {
    github: "https://github.com/Whatisthis8047",
    linkedIn: "https://linkedin.com",
    // facebook: "https://www.facebook.com",
    // x: "https://x.com",
    instagram: "https://www.instagram.com",
    // medium: "https://medium.com",
    // blogger: "https://blogger.com",
    // email: "mailto:devhudi@gmail.com",
    resume: "https://hudi.blog",
    // link: "https://hudi.blog",
  },
  useAbout: true,
  // See https://giscus.app/
  giscus: {
    repo: "devHudi/gatsby-starter-hoodie",
    repoId: "MDEwOlJlcG9zaXRvcnkzNjk4NjMzNTg=",
    category: "Comments",
    categoryId: "DIC_kwDOFguqvs4ChwGy",
    mapping: "pathname",
    strict: "0",
    reactionsEnabled: "1",
    inputPosition: "bottom",
    lang: "en",
  },
}
