module.exports = {
  title: "WhatIsThis' Blog?",
  description: "Welcome to my dev Blog",
  author: "Whatisthis",
  siteUrl: "https://what-is-this-blog.netlify.app/",
  links: {
    github: "https://github.com/Whatisthis8047",
    linkedIn: "https://www.linkedin.com/in/keonmo-lee-392674229/",
    // facebook: "https://www.facebook.com",
    // x: "https://x.com",
    instagram: "https://www.instagram.com/what_is_this_8047/",
    // medium: "https://medium.com",
    // blogger: "https://blogger.com",
    // email: "mailto:devhudi@gmail.com",
    resume: "https://oxidized-mimosa-7c3.notion.site/Keonmo-Lee-167ff41111c545da96c5f66b317f94fa?pvs=4",
    // link: "https://hudi.blog",
  },
  useAbout: true,
  // See https://giscus.app/
  giscus: {
    repo: "Whatisthis8047/gatsby-blog-source",
    repoId: "R_kgDONfi9Vg",
    category: "Comments",
    categoryId: "DIC_kwDONfi9Vs4ClWxZ",
    mapping: "pathname",
    strict: "0",
    reactionsEnabled: "1",
    inputPosition: "bottom",
    lang: "en",
    theme: "dark_dimmed",
  },
}
